config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  devise_for :users

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?

  post '/graphql', to: 'graphql#execute'

  root 'website#home'
  get '/app', to: 'webapp#init'

  # Admin
  authenticate :user, ->(u) { u.admin? } do
    namespace :admin do
      mount Sidekiq::Web => '/sidekiq'

      resources :users
      resources :blocks
      resources :languages
      resources :sentences
      resources :lessons
      resources :translations

      root to: 'users#index'
    end
  end

  get '/health', to: proc { [200, {}, ['healthy']] }
end

app/controllers/website_controller.rb
# frozen_string_literal: true

class WebsiteController < ApplicationController
  def home
    render 'home'
  end
end

app/views/website/home.html.erb
<div class="presentation content-inner">

  <div class="intro">
    <h1>Learning <strong>this</strong> new language is tricky, right?</h1>

    <p>I know the struggle. Living abroad, thinking I should start learning it soon, fix it for good... But other stuff always gets in the way.</p>

    <p>But it's actually easier than it seems. Learning the most common words of a language will already get you quite far along!</p>

  </div>

  <div class="what-is-that">
    <p>
      Well, that's the intention behind Dyno.
      <strong>Listen to a few useful words everyday</strong>, practise while commuting, while doing the dishes, while going to the gym...
      And finally overcome this unpleasant feeling of not understanding.
    </p>
  </div>

  <div class="container-button">
    <%= link_to "Try it now", app_path, class: 'button' %>
  </div>
</div>